spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useTimezone=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123

# 打印sql到控制台
logging:
  level:
    com.pan.demo.mapper: deg
mybatis-plus:
  type-aliases-package: com.pan.demo.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl